/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author javie
 */
public class InmobiliariaVista extends javax.swing.JFrame {

    
    public InmobiliariaVista() {
        initComponents();
        setSize(672,575);
        setTitle("TERRA Inmobiliaria"); // le damos titulo a la ventana del JFrame
        setLocationRelativeTo(null); // en ves de que nos aparesca en la esquina , nos aparece en el centro
        
        ImageIcon wallpaper =new ImageIcon("src/imagenes/TERRA_fondo1.jpg");  // creamos una variable de tipo ImageIcon y le decimos donde esta la imagen a utilizar
        
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(JLWallpaper.getWidth(), JLWallpaper.getHeight(), Image.SCALE_SMOOTH));
        //creamos una variable de tipo Icon y le decimos que a la imagen guardada en Wallpaper la tome
        //la re escale con el ancho y alto de la ventana del label y que lo haga de forma fluida
        
        JLWallpaper.setIcon(icono); // le pasamos el Icon al label 
        
        this.repaint(); // lo repintamos 
        
//        ImageIcon wallogo = new ImageIcon("src/imagenes/LOGOTIPO800x533.png");
//        Icon iconoLogo = new ImageIcon(wallogo.getImage().getScaledInstance(JLogo.getWidth(), JLogo.getHeight(), Image.SCALE_SMOOTH));
//        JLogo.setIcon(iconoLogo);
//        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLogo = new javax.swing.JLabel();
        jbienvenido = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        JLWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(JLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jbienvenido.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbienvenido.setForeground(new java.awt.Color(0, 153, 102));
        jbienvenido.setText("Bienvenido ");
        jbienvenido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbienvenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbienvenidoActionPerformed(evt);
            }
        });
        getContentPane().add(jbienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 120, 40));

        jTextField1.setBackground(new java.awt.Color(201, 237, 169));
        jTextField1.setFont(new java.awt.Font("Yu Mincho", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 153, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("TERRA Inmuebles");
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(201, 221, 124));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 220, 30));
        getContentPane().add(JLWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbienvenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbienvenidoActionPerformed
        MenuPrincipal mp= new MenuPrincipal(); // crear nueva variable tipo jframe
        InmobiliariaVista im= this; // crear variable de esta ventana
        mp.setVisible(true); // lanzar la nueva ventana
        im.dispose(); // cerrar la ventana anterior
        
    }//GEN-LAST:event_jbienvenidoActionPerformed
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InmobiliariaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InmobiliariaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InmobiliariaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InmobiliariaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InmobiliariaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLWallpaper;
    private javax.swing.JLabel JLogo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbienvenido;
    // End of variables declaration//GEN-END:variables


}
