/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author javie
 */
public class InmueblesVista extends javax.swing.JFrame {

    /**
     * Creates new form InmueblesVista
     */
    public InmueblesVista() {
        initComponents();
        setSize(458, 485);
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper =new ImageIcon("src/imagenes/TERRA_Inmuebles.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jlinmuvista.getWidth(), jlinmuvista.getHeight(), Image.SCALE_SMOOTH));
        jlinmuvista.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtinmualtu = new javax.swing.JTextField();
        jtinmutipo = new javax.swing.JTextField();
        jtinmusuper = new javax.swing.JTextField();
        jtinmuprec = new javax.swing.JTextField();
        jtinmuzona = new javax.swing.JTextField();
        jtinmupropietario = new javax.swing.JTextField();
        jtinmudirec = new javax.swing.JTextField();
        jbinmuguardar = new javax.swing.JButton();
        jbinmucerrar = new javax.swing.JButton();
        jlinmuvista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inmuebles");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 260, 10));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Superficie");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 80, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 70, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 70, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Zona");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 70, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Propietario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 80, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Direccion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 70, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Altura");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 70, 30));
        getContentPane().add(jtinmualtu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, -1));
        getContentPane().add(jtinmutipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, -1));
        getContentPane().add(jtinmusuper, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 180, -1));
        getContentPane().add(jtinmuprec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 120, -1));
        getContentPane().add(jtinmuzona, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 120, -1));
        getContentPane().add(jtinmupropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, -1));
        getContentPane().add(jtinmudirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 180, -1));

        jbinmuguardar.setForeground(new java.awt.Color(0, 0, 0));
        jbinmuguardar.setText("Guardar ");
        getContentPane().add(jbinmuguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jbinmucerrar.setForeground(new java.awt.Color(0, 0, 0));
        jbinmucerrar.setText("Cerrar");
        getContentPane().add(jbinmucerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jlinmuvista.setBackground(new java.awt.Color(255, 51, 153));
        getContentPane().add(jlinmuvista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InmueblesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InmueblesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InmueblesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InmueblesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InmueblesVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbinmucerrar;
    private javax.swing.JButton jbinmuguardar;
    private javax.swing.JLabel jlinmuvista;
    private javax.swing.JTextField jtinmualtu;
    private javax.swing.JTextField jtinmudirec;
    private javax.swing.JTextField jtinmuprec;
    private javax.swing.JTextField jtinmupropietario;
    private javax.swing.JTextField jtinmusuper;
    private javax.swing.JTextField jtinmutipo;
    private javax.swing.JTextField jtinmuzona;
    // End of variables declaration//GEN-END:variables
}
