/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author marti
 */
public class NewJFrame extends javax.swing.JFrame {

private Timer fadeTimer;
private float opacity = 1.0f; // Opacidad inicial (100% opaco)
private float opacity2 = 0.0f; 
private Timer animationTimer;
private JPanel panel;
private int xPos;

    public NewJFrame() {
        initComponents();
        fadeout();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartel = new javax.swing.JLabel();
        mipanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cartel.setText("jLabel1");

        mipanel.setBackground(new java.awt.Color(255, 0, 0));
        mipanel.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout mipanelLayout = new javax.swing.GroupLayout(mipanel);
        mipanel.setLayout(mipanelLayout);
        mipanelLayout.setHorizontalGroup(
            mipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        mipanelLayout.setVerticalGroup(
            mipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(cartel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mipanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mipanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(cartel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
   private void fadeout() {

        fadeTimer = new Timer(500, new ActionListener() { // Cambia la velocidad ajustando el valor (en milisegundos)
            @Override
            public void actionPerformed(ActionEvent e) {
                opacity -= 0.05f; // Disminuye gradualmente la opacidad
                mipanel.setOpaque(true);
                mipanel.setForeground(new java.awt.Color(0, 0, 0, (int) (255 * opacity)));
                mipanel.repaint();

                if (opacity <= 0.0f) {
                    fadeTimer.stop();
                    mipanel.setVisible(false); // Hacer que el JLabel sea invisible una vez que esté completamente desvanecido
                }
            }
        });
        fadeTimer.start();
    }

    private void fadein() {

        fadeTimer = new Timer(100, new ActionListener() { // Cambia la velocidad ajustando el valor (en milisegundos)
            @Override
            public void actionPerformed(ActionEvent e) {
                opacity2 += 0.05f; // Disminuye gradualmente la opacidad
                cartel.setOpaque(false);
                cartel.setForeground(new java.awt.Color(0, 0, 0, (int) (255 * opacity2)));
                cartel.repaint();

                if (opacity2 >= 1.0f) {
                    fadeTimer.stop();
                    cartel.setVisible(true); // Hacer que el JLabel sea visible una vez que esté completamente el pintado
                }
            }
        });
        fadeTimer.start();
    }

   
    private void mover() {
    panel = mipanel; // Cambia jPanel1 al nombre de tu JPanel
    xPos = panel.getX(); // Obtiene la posición inicial del panel
    
    animationTimer = new Timer(10, new ActionListener() { // Cambia la velocidad ajustando el valor (en milisegundos)
        @Override
        public void actionPerformed(ActionEvent e) {
            xPos -= 2; // Desplaza el panel 2 píxeles hacia la izquierda en cada paso
            panel.setLocation(xPos, panel.getY());
            panel.repaint();

            if (xPos <= -panel.getWidth()) {
                animationTimer.stop();
            }
        }
    });  
   animationTimer.start();
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartel;
    private javax.swing.JPanel mipanel;
    // End of variables declaration//GEN-END:variables
}
