/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesData.PropietarioData;
import Entidades.Propietario;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author javie
 */
public class PropietarioVista extends javax.swing.JFrame {

    /**
     * Creates new form PropietarioVista
     */
    public PropietarioVista() {
        initComponents();
        setSize(388, 455);
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper =new ImageIcon("src/imagenes/TERRA_Propietarios.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jlprovista.getWidth(), jlprovista.getHeight(), Image.SCALE_SMOOTH));
        jlprovista.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PropiID = new javax.swing.JTextField();
        PropiDNI = new javax.swing.JTextField();
        PropiNombre = new javax.swing.JTextField();
        PropiApe = new javax.swing.JTextField();
        PropiDom = new javax.swing.JTextField();
        PropiTel = new javax.swing.JTextField();
        GuardarPropi = new javax.swing.JButton();
        CerrarPropi = new javax.swing.JButton();
        jlprovista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nuevo Propietario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 170, 50));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 20));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Domicilio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Apellido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        PropiID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PropiIDKeyPressed(evt);
            }
        });
        getContentPane().add(PropiID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, -1));

        PropiDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PropiDNIKeyPressed(evt);
            }
        });
        getContentPane().add(PropiDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, -1));

        PropiNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PropiNombreKeyPressed(evt);
            }
        });
        getContentPane().add(PropiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, -1));

        PropiApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PropiApeKeyPressed(evt);
            }
        });
        getContentPane().add(PropiApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 140, -1));

        PropiDom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PropiDomKeyPressed(evt);
            }
        });
        getContentPane().add(PropiDom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 140, -1));

        PropiTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PropiTelKeyPressed(evt);
            }
        });
        getContentPane().add(PropiTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 140, -1));

        GuardarPropi.setText("Guardar");
        GuardarPropi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPropiActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarPropi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 100, 30));

        CerrarPropi.setText("Cerrar");
        CerrarPropi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarPropiActionPerformed(evt);
            }
        });
        getContentPane().add(CerrarPropi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 100, -1));
        getContentPane().add(jlprovista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void GuardarPropiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPropiActionPerformed
        if(PropiID.getText().length()<=0 || PropiDNI.getText().length()<=0 || PropiNombre.getText().length()<=0 || PropiApe.getText().length()<=0 || PropiDom.getText().length()<=0 || PropiTel.getText().length()<=0){ 
            JOptionPane.showMessageDialog(null, "Por favor ingrese datos en todos los campos antes de guardar" );
        }else{
        String id = PropiID.getText();               
        String dni = PropiDNI.getText();          
        String nombre= PropiNombre.getText();
        String apellido= PropiApe.getText();
        String domicilio= PropiDom.getText();
        int telefono = Integer.parseInt(PropiTel.getText());
        
        
         
        
        
        Propietario pro = new Propietario();
        
        pro.setIdpropietario(Integer.valueOf(id));
        pro.setDni(Integer.valueOf(dni));
        pro.setNombre(nombre);
        pro.setApellido(apellido);
        pro.setDomicilio(domicilio);
        pro.setTelefono(telefono);
        pro.setEstado(true);
        
        PropietarioData pr = new PropietarioData();
         pr.GuardarPropietario(pro);   
        }
            
        
         
        
         
    }//GEN-LAST:event_GuardarPropiActionPerformed

    private void CerrarPropiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarPropiActionPerformed
        dispose();
    }//GEN-LAST:event_CerrarPropiActionPerformed

    private void PropiIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PropiIDKeyPressed
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c)|| Character.isISOControl(c)){ 
            PropiID.setEditable(true);
            
        }else{
            PropiID.setEditable(false);
            JOptionPane.showMessageDialog(null, "ERROR: Por favor, ingrese solo NUMEROS en campo ID");
            return;
            
        }
    }//GEN-LAST:event_PropiIDKeyPressed

    private void PropiDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PropiDNIKeyPressed
         char c = evt.getKeyChar();
        
        if(Character.isDigit(c)|| Character.isISOControl(c)){ 
            PropiDNI.setEditable(true);
            
        }else{
            PropiDNI.setEditable(false);
            JOptionPane.showMessageDialog(null, "ERROR: Por favor, iingrese solo NUMEROS en campo DNI");
            return;
            
        }
    }//GEN-LAST:event_PropiDNIKeyPressed

    private void PropiTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PropiTelKeyPressed
       char c = evt.getKeyChar();
        
        if(Character.isDigit(c)|| Character.isISOControl(c)){ 
            PropiTel.setEditable(true);
            
        }else{
            PropiTel.setEditable(false);
            JOptionPane.showMessageDialog(null, "ERROR: Por favor, ingrese solo NUMEROS en campo Telefono");
            return;
            
        }
    }//GEN-LAST:event_PropiTelKeyPressed

    private void PropiNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PropiNombreKeyPressed
       char c = evt.getKeyChar();
        
        if(Character.isLetter(c)|Character.isWhitespace(c) || Character.isISOControl(c)){ 
            PropiNombre.setEditable(true);
            
        }else{
            PropiNombre.setEditable(false);
            JOptionPane.showMessageDialog(null, "ERROR: Por favor, ingrese solo LETRAS en campo Nombre");
            return;
            
        }
    }//GEN-LAST:event_PropiNombreKeyPressed

    private void PropiApeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PropiApeKeyPressed
        char c = evt.getKeyChar();
       
        if(Character.isLetter(c)||Character.isWhitespace(c) || Character.isISOControl(c)){ 
            PropiApe.setEditable(true);
            
        }else{
             PropiApe.setEditable(false);
            JOptionPane.showMessageDialog(null, "ERROR: Por favor, ingrese solo LETRAS en campo Apellido");
            return;
            
        }
    }//GEN-LAST:event_PropiApeKeyPressed

    private void PropiDomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PropiDomKeyPressed
         char c = evt.getKeyChar();
        
        if(Character.isAlphabetic(c)||Character.isWhitespace(c) || Character.isDigit(c) || Character.isISOControl(c)){ 
            PropiApe.setEditable(true);
            
        }else{
            PropiApe.setEditable(false);
            JOptionPane.showMessageDialog(null, "ERROR: Por favor, ingrese solo NUMEROS en campo Domicilio");
            return;
            
        }
    }//GEN-LAST:event_PropiDomKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PropietarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PropietarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PropietarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PropietarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PropietarioVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarPropi;
    private javax.swing.JButton GuardarPropi;
    private javax.swing.JTextField PropiApe;
    private javax.swing.JTextField PropiDNI;
    private javax.swing.JTextField PropiDom;
    private javax.swing.JTextField PropiID;
    private javax.swing.JTextField PropiNombre;
    private javax.swing.JTextField PropiTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlprovista;
    // End of variables declaration//GEN-END:variables
}
