/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;

//lola
public class Prueba2 extends javax.swing.JFrame {
    
    private Timer animationTimer;
    
    public Prueba2() {
        initComponents();
        setSize(672, 575);
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper =new ImageIcon("src/imagenes/LOGOTIPO800x533.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jlpadre.getWidth(), jlpadre.getHeight(), Image.SCALE_SMOOTH));
        jlpadre.setIcon(icono);
        this.repaint();
        
        ImageIcon wallpape =new ImageIcon("src/imagenes/titulo.png");
        Icon icon = new ImageIcon(wallpape.getImage().getScaledInstance(jltitulo.getWidth(), jltitulo.getHeight(), Image.SCALE_SMOOTH));
        jltitulo.setIcon(icon);
        this.repaint();
        
        ImageIcon wallpap =new ImageIcon("src/imagenes/inmu.jpg");
        Icon ico = new ImageIcon(wallpap.getImage().getScaledInstance(jlnuevaentrada.getWidth(), jlnuevaentrada.getHeight(), Image.SCALE_SMOOTH));
        jlnuevaentrada.setIcon(ico);
        this.repaint();
        
        ImageIcon wallpa =new ImageIcon("src/imagenes/TERRA_Busqueda_1024x683.jpg");
        Icon ic = new ImageIcon(wallpa.getImage().getScaledInstance(jlbusqueda.getWidth(), jlbusqueda.getHeight(), Image.SCALE_SMOOTH));
        jlbusqueda.setIcon(ic);
        this.repaint();
        
        ImageIcon wallpaperochi =new ImageIcon("src/imagenes/icono.png");
        Icon iconochi = new ImageIcon(wallpaperochi.getImage().getScaledInstance(jllogochi.getWidth(), jllogochi.getHeight(), Image.SCALE_SMOOTH));
        jllogochi.setIcon(iconochi);
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpadre = new javax.swing.JPanel();
        jlpadre = new javax.swing.JLabel();
        menu1entrada = new javax.swing.JPanel();
        jlmenuentrada = new javax.swing.JLabel();
        nuevaentrada = new javax.swing.JPanel();
        jbinmue = new javax.swing.JButton();
        jbinqui = new javax.swing.JButton();
        jbpropie = new javax.swing.JButton();
        jbcont = new javax.swing.JButton();
        jlnuevaentrada = new javax.swing.JLabel();
        busquedas = new javax.swing.JPanel();
        jbbusqinmu = new javax.swing.JButton();
        jbbusqcont = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jlbusqueda = new javax.swing.JLabel();
        jpbotones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jllogochi = new javax.swing.JLabel();
        jptitulo = new javax.swing.JPanel();
        jltitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpadre.setBackground(new java.awt.Color(102, 102, 102));
        jpadre.setLayout(new java.awt.CardLayout());
        jpadre.add(jlpadre, "card3");

        menu1entrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menu1entrada.add(jlmenuentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));

        jpadre.add(menu1entrada, "card2");

        nuevaentrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbinmue.setText("Inmuebles");
        jbinmue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbinmueActionPerformed(evt);
            }
        });
        nuevaentrada.add(jbinmue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jbinqui.setText("Inquilinos");
        jbinqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbinquiActionPerformed(evt);
            }
        });
        nuevaentrada.add(jbinqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jbpropie.setText("Propietarios");
        jbpropie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpropieActionPerformed(evt);
            }
        });
        nuevaentrada.add(jbpropie, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jbcont.setText("Contratos");
        jbcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcontActionPerformed(evt);
            }
        });
        nuevaentrada.add(jbcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));
        nuevaentrada.add(jlnuevaentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));

        jpadre.add(nuevaentrada, "card4");

        busquedas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbbusqinmu.setText("Inmuebles");
        jbbusqinmu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbusqinmuActionPerformed(evt);
            }
        });
        busquedas.add(jbbusqinmu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jbbusqcont.setText("Contratos");
        jbbusqcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbusqcontActionPerformed(evt);
            }
        });
        busquedas.add(jbbusqcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jButton2.setText("Inquilinos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        busquedas.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jButton3.setText("Propietarios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        busquedas.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));
        busquedas.add(jlbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 444));

        jpadre.add(busquedas, "card5");

        getContentPane().add(jpadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 520, 450));

        jpbotones.setBackground(new java.awt.Color(69, 125, 88));
        jpbotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Nueva Entrada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpbotones.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 211, -1, -1));

        jButton4.setText("Busqueda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jpbotones.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 286, 110, -1));
        jpbotones.add(jllogochi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 99));

        getContentPane().add(jpbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 550));

        jptitulo.setBackground(new java.awt.Color(153, 255, 51));

        javax.swing.GroupLayout jptituloLayout = new javax.swing.GroupLayout(jptitulo);
        jptitulo.setLayout(jptituloLayout);
        jptituloLayout.setHorizontalGroup(
            jptituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        jptituloLayout.setVerticalGroup(
            jptituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jptitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 0, 520, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       jpadre.removeAll();
       jpadre.add(nuevaentrada); 
       jpadre.repaint();
       jpadre.revalidate();
        
        animationTimer = new Timer(3, new ActionListener() {
        private int xPos = -nuevaentrada.getWidth();

        @Override
        public void actionPerformed(ActionEvent e) {
            xPos += 10; // Incrementa gradualmente la posición X

            if (xPos >= 0) {
                xPos = 0; // Asegura que no se desplace más allá de la posición final
                ((Timer) e.getSource()).stop(); // Detiene el temporizador
            }

            nuevaentrada.setLocation(xPos, nuevaentrada.getY());
            nuevaentrada.repaint();
        }

    });

    animationTimer.start();
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbinmueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbinmueActionPerformed
      //inmuebles
      InmueblesVista ivv= new InmueblesVista();
      ivv.setVisible(true);
      
    }//GEN-LAST:event_jbinmueActionPerformed

    private void jbinquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbinquiActionPerformed
     //inquilinos
     InquilinosVista iv= new InquilinosVista();
       iv.setVisible(true);
       
    }//GEN-LAST:event_jbinquiActionPerformed

    private void jbpropieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpropieActionPerformed
     //propietarios
     PropietarioVista pv= new PropietarioVista();
     pv.setVisible(true);
    }//GEN-LAST:event_jbpropieActionPerformed

    private void jbcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcontActionPerformed
     //contratos
     ContratosVistas cv= new ContratosVistas();
     cv.setVisible(true);
     
    }//GEN-LAST:event_jbcontActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
         jpadre.removeAll();
       jpadre.add(busquedas); 
       jpadre.repaint();
       jpadre.revalidate();
        
        animationTimer = new Timer(3, new ActionListener() {
        private int xPos = -busquedas.getWidth();

        @Override
        public void actionPerformed(ActionEvent e) {
            xPos += 10; // Incrementa gradualmente la posición X

            if (xPos >= 0) {
                xPos = 0; // Asegura que no se desplace más allá de la posición final
                ((Timer) e.getSource()).stop(); // Detiene el temporizador
            }

            busquedas.setLocation(xPos, busquedas.getY());
            busquedas.repaint();
        }

    });

    animationTimer.start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbbusqcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbusqcontActionPerformed
     BusquedaContratos bc = new BusquedaContratos();
     bc.setVisible(true);
    }//GEN-LAST:event_jbbusqcontActionPerformed

    private void jbbusqinmuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbusqinmuActionPerformed
      BusquedaInmuebles bi= new BusquedaInmuebles();
      bi.setVisible(true);
    }//GEN-LAST:event_jbbusqinmuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PropietarioBusqueda pb = new PropietarioBusqueda();
        pb.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InquilinosBuscar ib= new InquilinosBuscar();
        ib.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel busquedas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jbbusqcont;
    private javax.swing.JButton jbbusqinmu;
    private javax.swing.JButton jbcont;
    private javax.swing.JButton jbinmue;
    private javax.swing.JButton jbinqui;
    private javax.swing.JButton jbpropie;
    private javax.swing.JLabel jlbusqueda;
    private javax.swing.JLabel jllogochi;
    private javax.swing.JLabel jlmenuentrada;
    private javax.swing.JLabel jlnuevaentrada;
    private javax.swing.JLabel jlpadre;
    private javax.swing.JLabel jltitulo;
    private javax.swing.JPanel jpadre;
    private javax.swing.JPanel jpbotones;
    private javax.swing.JPanel jptitulo;
    private javax.swing.JPanel menu1entrada;
    private javax.swing.JPanel nuevaentrada;
    // End of variables declaration//GEN-END:variables
}
